# Generated by Django 5.1.6 on 2025-04-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_approved_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('business_analyst', 'Business Analyst'), ('dm_analyst', 'DM Analyst'), ('dm_executive', 'DM Executive')], max_length=20, null=True),
        ),
    ]
