# Generated by Django 5.1.6 on 2025-04-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_attendance_status_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day')], default='full', max_length=10),
        ),
    ]
