# Generated by Django 5.1.6 on 2025-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_analyst', '0002_leadtask_progress_percentage_leadtask_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='lead_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
