# Generated by Django 5.1.6 on 2025-04-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_analyst', '0003_dailyreport_lead_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
