# Generated by Django 5.1.6 on 2025-04-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_analyst', '0004_leadtask_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadtask',
            name='submitted_on',
            field=models.DateField(null=True),
        ),
    ]
