# Generated by Django 5.1.6 on 2025-04-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_excutive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='executive',
        ),
        migrations.AlterField(
            model_name='lead',
            name='platform',
            field=models.CharField(max_length=150),
        ),
    ]
