# Generated by Django 5.1.6 on 2025-04-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_excutive', '0003_lead_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
