# Generated by Django 5.1.6 on 2025-04-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_excutive', '0005_leadassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='assigned',
            new_name='is_assigned',
        ),
    ]
